import { Injectable, Logger } from '@nestjs/common';
import {
  planTransition,
  type LedgerEntryType,
  type LessonStatus,
} from '@tutorio/domain';
import { Prisma } from '@prisma/client';

/**
 * Writes to the credit ledger. Every method takes the caller's transaction so
 * a ledger row and the change that caused it commit together or not at all.
 *
 * The ledger is append-only: nothing here updates or deletes an entry. A
 * correction is a new, opposite-signed row.
 */
@Injectable()
export class LedgerService {
  private readonly logger = new Logger(LedgerService.name);

  /**
   * Appends one entry, or does nothing if that exact entry already exists.
   * Idempotency is enforced by the unique `idempotencyKey`, so a retry, a
   * double click, or a replayed job can never move a balance twice.
   */
  async append(
    tx: Prisma.TransactionClient,
    entry: {
      workspaceId: string;
      packageId: string;
      enrollmentId?: string | null;
      lessonId?: string | null;
      delta: number;
      type: LedgerEntryType;
      idempotencyKey: string;
      note?: string | null;
      createdById?: string | null;
    },
  ): Promise<boolean> {
    try {
      await tx.lessonCreditEntry.create({
        data: {
          workspaceId: entry.workspaceId,
          packageId: entry.packageId,
          enrollmentId: entry.enrollmentId ?? null,
          lessonId: entry.lessonId ?? null,
          delta: entry.delta,
          type: entry.type,
          idempotencyKey: entry.idempotencyKey,
          note: entry.note ?? null,
          createdById: entry.createdById ?? null,
        },
      });
      return true;
    } catch (error) {
      // P2002 = the key already exists, i.e. this effect was already recorded.
      if (
        error instanceof Prisma.PrismaClientKnownRequestError &&
        error.code === 'P2002'
      ) {
        this.logger.debug(
          `Ledger entry ${entry.idempotencyKey} already recorded`,
        );
        return false;
      }
      throw error;
    }
  }

  /**
   * Finds the package a lesson draws credits from. A lesson carries its package
   * directly once it was generated by one; otherwise the newest live package
   * covering the lesson's enrollment (or its group) is used.
   */
  async resolvePackageForLesson(
    tx: Prisma.TransactionClient,
    workspaceId: string,
    lesson: {
      id: string;
      packageId: string | null;
      enrollmentId: string | null;
      groupId: string | null;
    },
  ): Promise<{ id: string } | null> {
    if (lesson.packageId) {
      return tx.lessonPackage.findFirst({
        where: { id: lesson.packageId, workspaceId, deletedAt: null },
        select: { id: true },
      });
    }

    const studentId = lesson.enrollmentId
      ? (
          await tx.enrollment.findUnique({
            where: { id: lesson.enrollmentId },
            select: { studentId: true },
          })
        )?.studentId
      : undefined;

    return tx.lessonPackage.findFirst({
      where: {
        workspaceId,
        deletedAt: null,
        OR: [
          ...(studentId ? [{ studentId }] : []),
          ...(lesson.groupId ? [{ groupId: lesson.groupId }] : []),
        ],
      },
      orderBy: { purchasedAt: 'desc' },
      select: { id: true },
    });
  }

  /**
   * Records the credit effect of a lesson status transition and reports whether
   * the paid slot must be re-booked (an uncharged cancellation keeps the credit
   * but owes the student a replacement lesson).
   *
   * A lesson with no package behind it simply has no ledger effect — scheduling
   * must keep working before any package is bought.
   */
  async applyTransition(
    tx: Prisma.TransactionClient,
    params: {
      workspaceId: string;
      actorId: string;
      lesson: {
        id: string;
        packageId: string | null;
        enrollmentId: string | null;
        groupId: string | null;
        status: LessonStatus;
      };
      targetStatus: LessonStatus;
    },
  ): Promise<{ rebookReplacement: boolean; wrote: boolean }> {
    const pkg = await this.resolvePackageForLesson(
      tx,
      params.workspaceId,
      params.lesson,
    );
    if (!pkg) {
      return { rebookReplacement: false, wrote: false };
    }

    // A revert followed by the same transition again must not collide with the
    // original key, so entries of this type for this lesson are counted first.
    const priorEntryCount = await tx.lessonCreditEntry.count({
      where: { lessonId: params.lesson.id },
    });

    const plan = planTransition(
      params.lesson.status,
      params.targetStatus,
      params.lesson.id,
      priorEntryCount,
    );

    let wrote = false;
    if (plan.entry) {
      wrote = await this.append(tx, {
        workspaceId: params.workspaceId,
        packageId: pkg.id,
        enrollmentId: params.lesson.enrollmentId,
        lessonId: params.lesson.id,
        delta: plan.entry.delta,
        type: plan.entry.type,
        idempotencyKey: plan.entry.idempotencyKey,
        createdById: params.actorId,
      });
    }

    return { rebookReplacement: plan.rebookReplacement, wrote };
  }
}
